2022-01-30 13:11:49,438 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MywiZXhwIjoxNjQzNTIwMDY2LjI3ODM0N30.s7DMxblQ6cks9ov4MlzvuNe75VWShvN_dkuB9bP9KSc [GET] [in /Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/app/routes.py", line 249, in reset_password
    if form.validate_on_submit():
TypeError: FlaskForm.validate_on_submit() missing 1 required positional argument: 'self'
2022-01-30 13:14:50,118 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MywiZXhwIjoxNjQzNTIwMDY2LjI3ODM0N30.s7DMxblQ6cks9ov4MlzvuNe75VWShvN_dkuB9bP9KSc [GET] [in /Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/app/routes.py", line 249, in reset_password
    if form.validate_on_submit():
TypeError: FlaskForm.validate_on_submit() missing 1 required positional argument: 'self'
2022-01-30 13:15:16,197 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6MywiZXhwIjoxNjQzNTIwMzA4LjI3NjY3NH0.DiJUH2SM_eeDJMBNtKO-d6acWLHFeoU_ApzhNI71_kA [GET] [in /Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/rjin/OneDrive/MyNotes/a.python/microblog/app/routes.py", line 249, in reset_password
    if form.validate_on_submit():
TypeError: FlaskForm.validate_on_submit() missing 1 required positional argument: 'self'
2022-01-30 13:18:32,903 INFO: Microblog startup [in /Users/rjin/OneDrive/MyNotes/a.python/microblog/app/__init__.py:36]
